image: openjdk:latest

Java-build:
    stage: build
    script:
      - javac --module-path lib/javafx/lib --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.swing -cp lib/org.json.jar:lib/commons-io-2.0.jar src/**/*.java src/**/**/*.java src/**/**/**/*.java -d build/classes
      - jar --create --file build/codelab4.jar --main-class codelab4.App -C build/classes . src/resources 

JUnit-test:
    stage: test
    script:
      - javac --module-path lib/javafx/lib --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.swing -cp lib/org.json.jar:lib/commons-io-2.0.jar src/**/*.java src/**/**/*.java src/**/**/**/*.java -d build/classes
      - javac -cp build/classes:lib/junit-4.13.jar:lib/hamcrest-core-1.3.jar:lib/org.json.jar:lib/commons-io-2.0.jar test/**/*.java test/**/**/*.java -d build/classes
      - java -cp build/classes:lib/junit-4.13.jar:lib/hamcrest-core-1.3.jar:lib/org.json.jar:lib/commons-io-2.0.jar:test/resources codelab4.TestsRunner