sequenceDiagram

	activate Multicaster
	Multicaster->>Manager: REGI
	activate Multicaster
	opt No responds
		Manager--xMulticaster: Ø
	end
	activate Manager
	alt to many multicaster registered
		Manager--xMulticaster: RENO
	else is registered
		Manager-->>Multicaster: REOK
		deactivate Manager
		par
			loop every seconds
				activate Multicaster
				Multicaster->>World: DIFF
				deactivate Multicaster
			end
		end
		par register a new message
			Client->>+Multicaster: MESS
			activate Client
			Multicaster-->>-Client: ACKM
			deactivate Client
		end
		par register a new message
			Manager->>+Multicaster: MESS
			activate Manager
			Multicaster-->>-Manager: ACKM
			deactivate Manager
		end
		par get last messages
			Client->>+Multicaster: LAST nb-mess
			activate Client
			loop nb-mess times
				Multicaster-->>Client: OLDM
			end
			Multicaster-->>-Client: ENDM
			deactivate Client
		end
	end

    par weather request
        Client ->>Multicaster: RWET location
        activate Client
        alt response to client
            Multicaster--xClient : WERR
		else
            loop packet-count times
                Multicaster->>Client: WETI content
            end
            Multicaster->>Client : PEOF
        end
        deactivate Client
	end
	deactivate Multicaster
