/* all test files */
#include "test_cattar.c"
#include "test_cd.c"
#include "test_commons.c"
#include "test_commons_tar.c"
#include "test_commons_tsh.c"
#include "test_cptar.c"
#include "test_lstar.c"
#include "test_mkdirtar.c"
#include "test_mvtar.c"
#include "test_parser.c"
#include "test_redirections.c"
#include "test_rmdirtar.c"
#include "test_rmtar.c"
#include "test_tsh.c"
